image: python
env:
  - PYTHONPATH=/var/cache/drone
script:
 - sudo apt-get update -qq
 - sudo apt-get install python-numpy python-scipy python-cvxopt graphviz cython glpk libboost-dev
  - pip install -r requirements.txt -r optional-requirements.txt --use-mirrors
  - nosetests python/pydecode
  - cd python; py.test ../notebooks
notify:
  email:
    recipients:
      - sasha.rush@gmail.com