image: scivm/scientific-python-2.7
env:
  - PYTHONPATH=/var/cache/drone
script:
  - source /opt/ve/bin/activate
  - ls .
  - apt-get install -y glpk
  - pip install pulp
  - python setup.py config
  - python setup.py build_ext --inplace
  - nosetests python/pydecode/test/
notify:
  email:
    recipients:
      - sasha.rush@gmail.com