language: python
python:
  - "2.7"
# command to install dependencies
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphviz
install:
  - pip install -r requirements.txt -r optional-requirements.txt --use-mirrors
  - pip install .

# command to run tests
script:
  - nosetests python/pydecode
  - cd python; py.test ../notebooks